### ISSUE TITLE
Should it error out on non-existing file?

### ISSUE THREAD

**Issue by Ambrevar** [Shinmera/trivial-mimes#10]
Currently `(mime "non-existing-file")` returns `"application/octet-stream"`.  Shouldn't it return NIL instead?

**Comment by Shinmera** [comment]
See the documentation. It returns the default if the lookup fails by either method.

**Comment by Shinmera** [comment]
I'm not sure if it should check for existence. It is a valid use-case to determine the type from just a path without having an actual file.

**Comment by Ambrevar** [comment]
OK, makes sense.
