### ISSUE TITLE
Replace `probe-file` with `uiop:file-exists-p`

### ISSUE THREAD

**Issue by Ambrevar** [Shinmera/trivial-mimes#7]
Otherwise it errors out if the pathname / path contains a wildcard, such as `*`.

**Comment by Ambrevar** [comment]
Friendly ping! :)
I'd like to leverage this library for https://gitlab.com/ambrevar/fof ;)

**Comment by Shinmera** [comment]
I'm not sure I want to do this. It should be up to the user to ensure that the pathname passed in isn't wild. If anything, I'd rather insert a check that signals an error when it is wild.

**Comment by Ambrevar** [comment]
My bad, I just remembered that `uiop:file-exists-p` has the same
wildcard issue.

You are right, it's fine to let the user fix the pathname at the call site.
