### ISSUE TITLE
Return the MIME encoding?

### ISSUE THREAD

**Issue by Ambrevar** [Shinmera/trivial-mimes#8]
Would it be possible to add a function that returns the MIME encoding?

Maybe see `file` and `magicffi` which can do that.

**Comment by Ambrevar** [comment]
Also the MIME description would be great.  `magicffi` can also return it (with `(magicffi:magic-open '(:symlink))` instead of `(magicffi:magic-open '(:symlink :mime))` for instance).

**Comment by Shinmera** [comment]
I don't think it's possible to determine the encoding automatically in a reliable manner, let alone a manner that is easy to implement for a `trivial-` library.

**Comment by Ambrevar** [comment]
I'm not sure either.

The repo contains a MIME database, how did you get it?
Would it be possible to have a similar database with MIME encoding and description?

**Comment by Shinmera** [comment]
The database is taken from a standard linux distribution. It is a static assignment of file types to mime-types and depends on the file type being correct. A file type can contain content in various encodings, sometimes even multiple at once. It is necessary to inspect and parse the file itself to determine the correct content type.

If we cannot parse the file type, we can only perform heuristics, which I do not think is a good thing to rely on, and would regardless still be difficult to implement.
